openapi: 3.0.3
info:
  title: 混合目录结构API示例
  description: 包含根目录、单层目录、多层目录的接口组织示例
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: 主服务地址

tags:  
  # 单层目录（一级标签，无嵌套）
  - name: 单层用户管理
    description: 仅一层目录的用户相关接口
  - name: 单层订单处理
    description: 仅一层目录的订单相关接口
  
  # 二层目录（二级嵌套）
  - name: 多层商品管理/基础信息
    description: 商品管理下的基础信息接口
  - name: 多层商品管理/库存操作
    description: 商品管理下的库存相关接口
  
  # 三深层级（三级嵌套）
  - name: 系统管理/权限控制/角色管理
    description: 三级嵌套的角色管理接口
  - name: 系统管理/权限控制/资源分配
    description: 三级嵌套的资源分配接口
  - name: 系统管理/日志审计/操作日志
    description: 三级嵌套的操作日志接口

paths:
  /health:
    get:
      tags:
      summary: 服务健康检查
      description: 直接在根目录的接口，无任何层级目录
      responses:
        '200':
          description: 服务正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"

  # 单层目录接口
  /users/simple:
    get:
      tags:
        - 单层用户管理
      summary: 获取简单用户列表
      description: 仅在单层目录中的接口
      responses:
        '200':
          description: 成功返回用户列表

  /orders/basic:
    post:
      tags:
        - 单层订单处理
      summary: 创建基础订单
      description: 仅在单层目录中的订单接口
      responses:
        '201':
          description: 订单创建成功

  # 二级多层目录接口
  /products/info:
    get:
      tags:
        - 二层商品管理/基础信息
      summary: 获取商品基础信息
      description: 二级目录下的接口
      responses:
        '200':
          description: 成功返回商品信息

  /products/stock:
    put:
      tags:
        - 二层商品管理/库存操作
      summary: 更新商品库存
      description: 二级目录下的库存接口
      responses:
        '200':
          description: 库存更新成功

  # 三级多层目录接口
  /system/roles:
    get:
      tags:
        - 三层系统管理/权限控制/角色管理
      summary: 获取角色列表
      description: 三级目录下的角色管理接口
      responses:
        '200':
          description: 成功返回角色列表

  /system/resources:
    post:
      tags:
        - 三层系统管理/权限控制/资源分配
      summary: 分配系统资源
      description: 三级目录下的资源分配接口
      responses:
        '200':
          description: 资源分配成功

  /system/logs/operation:
    get:
      tags:
        - 三层系统管理/日志审计/操作日志
      summary: 查询操作日志
      description: 三级目录下的操作日志接口
      responses:
        '200':
          description: 成功返回操作日志

components:
  schemas:
    BasicResponse:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: "操作成功"
        data:
          type: object
